language: java

jdk:
  - oraclejdk8
 
env:
  - TEST_DIR=code/myblog_api
  
services:
  - mysql

before_install:
  - mysql -uroot -e 'CREATE DATABASE myblog_test;'
  - mysql -uroot < design/schema.sql

script: cd $TEST_DIR && mvn install && mvn test